name: Test CI
on:
  push:
    paths:
    - '**.ring'
    - '**.dll'
    - '**.so'
    - '**.dylib'
    - '.github/workflows/testCI.yml'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel, windows-latest, windows-11-arm ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Run Ring Argon2 tests
      uses: ysdragon/ring-action@v1.2.3
      with:
        file: "src/argon2_test.ring"